# Site wide configuration

title: In Development
description: 
logo:  # 120x120 px default image used for Twitter summary card
teaser:  # 400x250 px default teaser image used in image archive grid
locale:
#url: http://localhost:4000
url: http://fitmusician.com

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Nicholas Brewer
  email: bricknewer@gmail.com
  twitter: 
  google:
    ad-client:
    ad-slot:
  bio: 
  avatar:  # 160x160 px image for author byline
disqus-shortname:

#gems:
#  - jekyll-gallery-generator

exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]

# Gallery Settings

gallery:
  # path to the gallery
  dir: 
  # title for gallery index

  title: 
  # title prefix for gallery page. title=title_prefix+gallery_name
  title_prefix: ""
  # field to control sorting of galleries for the index page
  # (possible values are: title, date_time, best_image)
  sort_field: "best_image"
  # sizes for thumbnails
  thumbnail_size:
    x: 300
    y: 200
  # custom configuration for individual gallery
  # best_image is image for the index page (defaults to last image)
  galleries:
    
